# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/trainerservice', './trainer' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/challengeservice', './challenge' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/battleservice', './battle' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/frontend', './frontend' ]
# images:
# - 'gcr.io/$PROJECT_ID/trainerservice'
# - 'gcr.io/$PROJECT_ID/challengeservice'
# - 'gcr.io/$PROJECT_ID/battleservice'
# - 'gcr.io/$PROJECT_ID/frontend'


# USAGE:
# GCP zone and GKE target cluster must be specified as substitutions
# Example invocation:
# `gcloud builds submit --config=cloudbuild.yaml --substitutions=_ZONE=us-central1-b,_CLUSTER=demo-app-staging .`

steps:
- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold:v0.20.0'
  entrypoint: 'bash'
  args: 
  - '-c'
  - > 
    gcloud container clusters get-credentials --zone=$_ZONE $_CLUSTER;
    skaffold run -p gcb -f=skaffold.yaml --default-repo=gcr.io/$PROJECT_ID;