apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: trainerservice
    context: trainer
  - image: challengeservice
    context: challenge
  - image: battleservice
    context: battle
  - image: frontend
    context: frontend

deploy:
  kubectl:
    manifests:
    - kubernetes-manifest/*.yaml

profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: pokemon-microservice-262723
  - name: local
    build: 
      local: