apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: pokemon-microservice-v2
build:
  artifacts:
  - image: trainerservice
    context: trainer
  - image: challengeservice
    context: challenge
  - image: frontend
    context: frontend

deploy:
  kubectl:
    manifests:
    - kubernetes-manifest/*.yaml
