steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/trainerservice', './trainer' ]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/trainerservice:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy:stable"
  args:
  - run
  - --filename=./kubernetes-manifest/trainer.yaml
  - --image=gcr.io/$PROJECT_ID/trainerservice:latest
  - --location=$_ZONE
  - --cluster=$_CLUSTER