apiVersion: apps/v1
kind: Deployment
metadata:
  name: challengeservice
spec:
  selector:
    matchLabels:
      app: challengeservice
  template:
    metadata:
      labels:
        app: challengeservice
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: challenge
        image: gcr.io/pokemon-microservice-262723/challengeservice
        # image: challengeservice
        ports:
        - containerPort: 50052
        env:
        - name: PORT
          value: "50052"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052"]
          initialDelaySeconds: 60
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052"]
          initialDelaySeconds: 60
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        resources:
          requests:
            cpu: 75m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: challengeservice
spec:
  type: ClusterIP
  selector:
    app: challengeservice
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052