apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainerservice
build:

spec:
  selector:
    matchLabels:
      app: trainerservice
  template:
    metadata:
      labels:
        app: trainerservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: trainer
        image: trainerservice:1.0
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trainerservice
spec:
  type: ClusterIP
  selector:
    app: trainerservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051