apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainerservice
build:

spec:
  selector:
    matchLabels:
      app: trainerservice
  template:
    metadata:
      labels:
        app: trainerservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: trainer
        image: gcr.io/pokemon-microservice-262723/trainerservice
        # image: trainerservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 60
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 60
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trainerservice
spec:
  type: ClusterIP
  selector:
    app: trainerservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051